@startuml
'https://plantuml.com/class-diagram

class AppLauncher {
   +{static} void main(String[] args)
   +void start(Stage primaryStage)
}

package javafx.application {
   .Application <|-- AppLauncher
}

class AppMenuBar {
    +AppMenuBar()
}

package javafx.scene.control {
    .MenuBar <|-- AppMenuBar
}

class CanvasState {

    - List<Render<? extends MovableDrawing>> renders

    + void addRenderFigures(Collection<Render<? extends MovableDrawing>> toAdd)
    + void deleteRenderFigures(Collection<Render<? extends MovableDrawing>> toRemove)
    + void moveToFront( List<Render<? extends MovableDrawing>> selectedList)
    + void moveToBack( List<Render<? extends MovableDrawing>> selectedList)
    + List<Render< ? extends MovableDrawing>> renderFigures()
}

class MainFrame {

    +MainFrame(CanvasState canvasState)
}
package javafx.scene.layout {
    .VBox <|-- MainFrame
}

@enduml