@startuml
'https://plantuml.com/sequence-diagram

package javafx.scene.control{
     class ToggleButton
     class ToggleGroup
}

package Buttons {

interface ButtonsOption {

    +void mousePressed(Point eventPoint)
    +void mouseReleased(Point eventPoint)
    +void mouseClicked(Point eventPoint)
    +void mouseMoved(Point eventPoint)
    +void mouseDragged(Point startPoint, Point eventPoint)
    +void mouseClickAndDrag(Point pressedPoint, Point releasePoint)

}

abstract class ToggleOptionButton extends ToggleButton implements ButtonsOption{

}

class FigureButtons<F extends MovableDrawing> extends ToggleOptionButton{
        - RendererCreator<F> rendererCreator
        - List<Render<? extends MovableDrawing>> renderList
        - Point startPoint

        + FigureButtons(String buttonName, List<Render<? extends MovableDrawing>> renderList,
        RendererCreator<F> rendererCreator )
        + Render<F> createRenderer(Point startPoint, Point endPoint)
        + void mousePressed(Point eventPoint)
        + void mouseReleased(Point eventPoint)
}

class SelectButton extends ToggleOptionButton {
        - List<Render<? extends MovableDrawing>> selectedList
        - List<Render<? extends MovableDrawing>> renderList
        - Rectangle imaginaryRect
        - Point lastPosition

        + SelectButton(String buttonName, List<Render<? extends MovableDrawing>> selectedList,
        List<Render<? extends MovableDrawing>> renderList)
        + void mousePressed(Point eventPoint)
        + void mouseClicked(Point eventPoint)
        + void mouseDragged(Point startPoint, Point eventPoint)
        + void mouseClickAndDrag(Point pressedPoint, Point releasePoint)
}

class ToggleOptionGroup extends ToggleGroup{
    + ToggleOptionButton getSelectedOption()
}

@enduml